/* Dependency-free engine, also loaded by the shared Node/Python fixture suite. */
(function(root){
'use strict';
const REDACTED='[REDACTED]';
const defaults={redact_fragments:true,redact_private_hosts:true,redact_all_titles:false,detect_emails:false,detect_tokens:false,detect_paths:false,redact_all_strings:false,strip_url_paths:false,drop_query:false};
const lists=['redact_text_keys','drop_keys','redact_domains','query_allowlist'];
function normalize(input){const data=input??{};if(typeof data!=='object'||Array.isArray(data))throw Error('policy must be an object');if(Object.keys(data).some(k=>!(k in defaults)&&!lists.includes(k)))throw Error('unsupported policy fields');const out={};for(const k of lists){const values=k in data?data[k]:[];if(!Array.isArray(values)||values.some(v=>typeof v!=='string'||!v))throw Error(k+' must contain non-empty strings');out[k]=[...new Set(values.map(v=>k==='redact_domains'?v.toLowerCase():v))].sort();}for(const [k,d] of Object.entries(defaults)){const value=k in data?data[k]:d;if(typeof value!=='boolean')throw Error(k+' must be a boolean');out[k]=value;}return out;}
function strictPolicy(){return normalize({redact_all_titles:true,redact_all_strings:true,strip_url_paths:true,drop_query:true});}
function ipv6(value){let host=value.split('%')[0];if(host.includes('.')){const cut=host.lastIndexOf(':');const bits=host.slice(cut+1).split('.').map(Number);if(bits.length!==4||bits.some(v=>!Number.isInteger(v)||v<0||v>255))return null;host=host.slice(0,cut+1)+((bits[0]<<8)|bits[1]).toString(16)+':'+((bits[2]<<8)|bits[3]).toString(16);}const pair=host.split('::');if(pair.length>2)return null;const a=pair[0]?pair[0].split(':'):[],b=pair[1]?pair[1].split(':'):[];const words=pair.length===2?[...a,...Array(Math.max(0,8-a.length-b.length)).fill('0'),...b]:a;if(words.length!==8||words.some(x=>!/^\b[0-9a-f]{1,4}$/i.test(x)))return null;return words.reduce((v,x)=>(v<<16n)+BigInt(parseInt(x,16)),0n);}
function privateHost(input){let host;try{host=decodeURIComponent(input).toLowerCase().replace(/\.$/,'').replace(/^\[|\]$/g,'');}catch{return true;}if(host==='localhost'||host==='localhost.localdomain'||host.endsWith('.local')||(!host.includes('.')&&!host.includes(':')))return true;if(host.includes(':')){const v=ipv6(host);if(v===null)return false;if((v>>32n)===65535n){return privateHost([24n,16n,8n,0n].map(s=>Number((v>>s)&255n)).join('.'));}return v===0n||v===1n||(v>>121n)===126n||(v>>118n)===1018n||(v>>120n)===255n||(v>>96n)===0x20010db8n;}
const parts=host.split('.');if(/^(?:0x[0-9a-f]+|[0-9]+)(?:\.(?:0x[0-9a-f]+|[0-9]+))*$/.test(host)&&(parts.length!==4||parts.some(x=>x.startsWith('0x')||(x.length>1&&x.startsWith('0')))))return true;if(parts.length!==4||parts.some(x=>!/^\d+$/.test(x)||Number(x)>255))return false;const [a,b,c]=parts.map(Number);return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===168||(b===0&&(c===0||c===2))))||(a===198&&(b===18||b===19||(b===51&&c===100)))||(a===203&&b===0&&c===113)||a>=224;}
function retained(value){const counts={string_fields:0,fully_redacted_strings:0,numeric_fields:0,boolean_fields:0,null_fields:0};function walk(v){if(v===null)counts.null_fields++;else if(Array.isArray(v))v.forEach(walk);else if(typeof v==='object')Object.values(v).forEach(walk);else if(typeof v==='string'){counts.string_fields++;if(v===REDACTED)counts.fully_redacted_strings++;}else if(typeof v==='number')counts.numeric_fields++;else if(typeof v==='boolean')counts.boolean_fields++;}walk(value);return counts;}
function sanitize(input,rawPolicy){if(!input||typeof input!=='object')throw Error('session export must contain an object or array');const rules=normalize(rawPolicy),changes=Object.fromEntries(['removed_credentials','removed_query_segments','redacted_url_paths','redacted_query_values','redacted_fragments','redacted_hosts','redacted_text_fields','dropped_fields','invalid_urls','non_web_urls','detected_email','detected_token','detected_windows_path','detected_unix_path'].map(k=>[k,0])),review=[];
function url(value){try{const match=value.trimStart().match(/^([A-Za-z][A-Za-z0-9+.-]*):\/\/([^/?#]*)([^?#]*)(?:\?([^#]*))?(?:#(.*))?$/s);if(!match){changes.non_web_urls++;return REDACTED;}const scheme=match[1].toLowerCase();if(!['http','https'].includes(scheme)){changes.non_web_urls++;return REDACTED;}let authority=match[2],credentials='';const at=authority.lastIndexOf('@');if(at>=0){credentials=authority.slice(0,at);authority=authority.slice(at+1);}let host,port='';if(authority.startsWith('[')){const end=authority.indexOf(']');if(end<0)throw Error('invalid host');host=authority.slice(1,end);const tail=authority.slice(end+1);if(tail){if(!tail.startsWith(':'))throw Error('invalid authority');port=tail.slice(1);}if(ipv6(host)===null)throw Error('invalid IPv6');}else{const bits=authority.split(':');if(bits.length>2)throw Error('invalid host');[host,port='']=bits;}if(port&&(!/^\d+$/.test(port)||Number(port)>65535))throw Error('invalid port');host=decodeURIComponent(host).toLowerCase().replace(/\.$/,'');if(!host){changes.non_web_urls++;return REDACTED;}if(rules.redact_domains.some(d=>host===d.replace(/\.$/,'')||host.endsWith('.'+d.replace(/\.$/,'')))||(rules.redact_private_hosts&&privateHost(host))){changes.redacted_hosts++;return scheme+'://[REDACTED-HOST]/';}if(credentials)changes.removed_credentials++;if(match[4]&&rules.drop_query)changes.removed_query_segments+=match[4].split('&').length;if(match[3]&&match[3]!=='/'&&rules.strip_url_paths)changes.redacted_url_paths++;const query=rules.drop_query?'':(match[4]||'').split('&').filter((x,i,a)=>x||a.length>1).map(segment=>{const split=segment.indexOf('='),name=split<0?segment:segment.slice(0,split);let decoded;try{decoded=decodeURIComponent(name);}catch{decoded=name;}if(rules.query_allowlist.includes(decoded))return segment;changes.redacted_query_values++;return split<0?name:name+'='+REDACTED;}).join('&');let fragment=match[5]||'';if(fragment&&rules.redact_fragments){fragment=REDACTED;changes.redacted_fragments++;}const netloc=(host.includes(':')?'['+host+']':host)+(Number(port)?':'+Number(port):'');return scheme+'://'+netloc+(rules.strip_url_paths?'/':match[3])+(query?'?'+query:'')+(fragment?'#'+fragment:'');}catch{changes.invalid_urls++;return REDACTED;}}
function text(value,path){if(rules.redact_all_strings){changes.redacted_text_fields++;return REDACTED;}let out=value;const apply=(enabled,name,pattern,replacement)=>{if(!enabled)return;let count=0;out=out.replace(pattern,()=>{count++;return replacement;});if(count){changes['detected_'+name]+=count;review.push({rule:name,path,action:'redacted'});}};
apply(rules.detect_emails,'email',/(?<![\w.+-])[\w.+-]+@[\w-]+(?:\.[\w-]+)+/gi,'[REDACTED-EMAIL]');apply(rules.detect_tokens,'token',/(?:\bBearer\s+)?(?:eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}|gh[pousr]_[A-Za-z0-9]{20,}|[A-Za-z0-9_-]{32,})/g,'[REDACTED-TOKEN]');apply(rules.detect_paths,'windows_path',/\b[A-Za-z]:\\(?:[^\\\r\n]+\\)*[^\\\r\n]*/g,'[REDACTED-PATH]');apply(rules.detect_paths,'unix_path',/(?<![:/])\/(?:Users|home|var|tmp)\/[^\s"']+/g,'[REDACTED-PATH]');return out;}
function walk(v,path='$'){if(Array.isArray(v))return v.map((x,i)=>walk(x,path+'['+i+']'));if(v&&typeof v==='object'){const entries=[];for(const [key,item] of Object.entries(v)){const next=path+'.'+key;if(rules.drop_keys.includes(key)){changes.dropped_fields++;continue;}if(typeof item==='string'&&['url','uri','href'].includes(key.toLowerCase()))entries.push([key,url(item)]);else if(typeof item==='string'&&(rules.redact_text_keys.includes(key)||(rules.redact_all_titles&&['title','name','description','body','note','notes','summary'].includes(key.toLowerCase())))){changes.redacted_text_fields++;entries.push([key,REDACTED]);}else entries.push([key,walk(item,next)]);}return Object.fromEntries(entries);}return typeof v==='string'?text(v,path):v;}
const output=walk(input);return {output,audit:{schema_version:1,changes,review_queue:review,retained_summary:retained(output),review_required:true,boundary:'Explicit rules cannot prove anonymity; inspect the sanitized copy.'}};}
const api={sanitize,normalize,strictPolicy,privateHost};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.SessionScrubber=api;
})(globalThis);
