const $=id=>document.getElementById(id);const engine=SessionScrubber;
let records=[];
$('policy').value=JSON.stringify(engine.normalize({}),null,2);
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function button(label,action){const b=document.createElement('button');b.textContent=label;b.onclick=action;return b;}
function preview(title,value){const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent=title;const pre=document.createElement('pre');pre.textContent=JSON.stringify(value,null,2);details.append(summary,pre);return details;}
function run(){try{const rules=engine.normalize(JSON.parse($('policy').value));$('results').replaceChildren();for(const {name,data} of records){const a=engine.sanitize(data,rules),b=engine.sanitize(data,engine.strictPolicy()),card=document.createElement('article'),heading=document.createElement('h2');heading.textContent=name;card.append(heading,preview('Original sensitive input',data));const pair=document.createElement('div');pair.className='pair';for(const [label,result,suffix] of [['Selected policy',a,'selected'],['Strict sharing policy',b,'strict']]){const panel=document.createElement('section'),h=document.createElement('h3');h.textContent=label;const summary=document.createElement('p'),c=result.audit.retained_summary;summary.textContent=c.string_fields+' string fields; '+c.fully_redacted_strings+' fully redacted. Retains '+c.numeric_fields+' numbers, '+c.boolean_fields+' booleans and '+c.null_fields+' nulls. Field names and structure remain.';const changes=document.createElement('p');changes.textContent=Object.entries(result.audit.changes).filter(([,n])=>n).map(([key,n])=>key.replaceAll('_',' ')+': '+n).join('; ')||'No rule changes observed';panel.append(h,summary,changes,preview('Inspect sanitized values',result.output),button('Download '+suffix+' sanitized',()=>download(name+'.'+suffix+'.sanitized.json',result.output)),button('Download '+suffix+' audit',()=>download(name+'.'+suffix+'.audit.json',result.audit)));pair.append(panel);}card.append(pair);$('results').append(card);}$('status').textContent=records.length+' exports compared locally. Strict policy is not an anonymity guarantee.';}catch(error){$('status').textContent='Error: '+error.message;}}
$('compare').onclick=()=>{try{records=[{name:'pasted-export',data:JSON.parse($('input').value)}];run();}catch(error){$('status').textContent='Error: '+error.message;}};
$('default').onclick=()=>{$('policy').value=JSON.stringify(engine.normalize({}),null,2);if(records.length)run();};$('strict').onclick=()=>{$('policy').value=JSON.stringify(engine.strictPolicy(),null,2);if(records.length)run();};$('recompare').onclick=run;
$('demo').onclick=()=>{$('input').value=JSON.stringify({tabs:[{title:'Fictional example',url:'https://example.test/private-path?token=fictional#section',note:'Fictional note',pinned:true}]},null,2);$('compare').click();};
async function files(items){try{records=[];for(const file of items)records.push({name:file.name,data:JSON.parse(await file.text())});run();}catch(error){$('status').textContent='Error: '+error.message;}}
$('files').onchange=e=>files(e.target.files);const drop=$('drop');for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>e.preventDefault());drop.addEventListener('drop',e=>{e.preventDefault();files(e.dataTransfer.files);});
$('save-policy').onclick=()=>{try{download('session-policy.json',engine.normalize(JSON.parse($('policy').value)));}catch(error){$('status').textContent='Error: '+error.message;}};
$('policy-file').onchange=async e=>{try{if(!e.target.files.length)return;$('policy').value=JSON.stringify(engine.normalize(JSON.parse(await e.target.files[0].text())),null,2);if(records.length)run();}catch(error){$('status').textContent='Error: '+error.message;}};
